---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pr-pipeline
spec:
  tasks:   
    - name: test-oc-command
      taskRef:
        name: openshift-client
      params:
        - name: ARGS
          value: ["version"]
           
