---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pr-pipeline
spec:
  params:
    - name: SCRIPT
      description: script
  tasks:
    - name: test-oc-script
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: "$(params.SCRIPT)"
            
           
