---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-client
spec:
  params:
  - name: SCRIPT
    description: The OpenShift CLI arguments to run
    type: string
    default: "oc $@"
  - name: ARGS
    description: The OpenShift CLI arguments to run
    type: array
    default:
    - "help"
  - name: VERSION
    description: The OpenShift Version to use
    type: string
    default: "4.6"
  resources:
    inputs:
      - name: source
        type: git
        optional: true
  steps:
    - name: oc
      image: quay.io/openshift/origin-cli:$(params.VERSION)
      command: ["sh"]
      args:
        - "-c"
        - "oc login -u apikey -p 8VQCc9qtBOI-tcJrJHqOoBqWoTJnlF7ifEFImzgz91Zn --server=https://c114-e.us-south.containers.cloud.ibm.com:32369; oc new-project pipeline-proj"
