---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-client
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: cli
    tekton.dev/displayName: "openshift client"
spec:
  inputs:
    params:
    - name: SCRIPT
      description: The OpenShift CLI arguments to run
      type: string
    - name: ARGS
      description: The OpenShift CLI arguments to run
      type: array
      default:
      - "help"
    - name: VERSION
      description: The OpenShift Version to use
      type: string
      default: "4.6"
  steps:
    - name: oc
      image: quay.io/openshift/origin-cli:$(input.params.VERSION)
      script: $(inputs.params.SCRIPT)
